# Site settings
title: UPC Linux
email: upclinux@163.com
description: > # this means to ignore newlines until "baseurl:"
  中国石油大学（华东） Linux 协会
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://upclinux.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: upclinux
qqgroup_id: 279310694

# Build settings
markdown: kramdown
