# Site settings
title: UPC Linux
email: upclinux@163.com
description: 中国石油大学 (华东) Linux 协会
footnote: > # this means to ignore newlines until "baseurl:"
  中国石油大学 (华东) Linux 协会<br><br>自豪地采用 Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://upclinux.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title
paginate: 5
timezone: Asia/Shanghai
#twitter_username: jekyllrb
github_username: upclinux
qqqun_name: "QQ 群 (279310694)"
qqqun_idkey: e47c6b546d3373c09f7eaa8d4173728a513975ed2d0ec20106e83cfb11a3bf08
#weibo_username: upclinux
#weibo_userid: 0000

# Build settings
markdown: kramdown
